from typing import Tuple

BTCUSDT = 'BTCUSDT'
ETHBTC = 'ETHBTC'
LTCBTC = 'LTCBTC'
ABOBABTC = 'ABOBABTC'
DGBBTC = 'DGBBTC'
DOGEBTC = 'DOGEBTC'

SYMBOL_PAIRS: Tuple[str, ...] = (BTCUSDT, ETHBTC, LTCBTC, ABOBABTC, DGBBTC, DOGEBTC)

BASE_INTERVAL_HOUR = 'hour'

BINANCE_INTERVAL_MAPPING = {BASE_INTERVAL_HOUR: '1h'}
